# Generated by Django 5.1 on 2026-06-11 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(db_index=True, max_length=128, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField(verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='メーカー名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommended', models.BooleanField(default=False, verbose_name='おススメ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='カテゴリ')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='Purchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文詳細ID')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item', verbose_name='商品')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase', verbose_name='注文')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='注文者'),
        ),
        migrations.CreateModel(
            name='Itemincart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='会員')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
    ]
